version: '3'

services:
   
  cockroachdb:
    container_name: cockroach
    image: cockroachdb/cockroach:latest-v22.2
    command: start-single-node --insecure --store=attrs=ssd,path=/var/lib/cockroach/
    restart: "no"
    volumes:
      - data:/var/lib/cockroach
    environment:
      COCKROACH_DATABASE: bbs
      COCKROACH_USER: root
      COCKROACH_PASSWORD: 123456
    expose:
      - "8080"
      - "26257"
    ports:
      - "26257:26257"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  data: