// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package bbs

import (
	"time"
)

type User struct {
	ID        string
	Email     string
	Username  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
